### ISSUE TITLE
iBeacon exits are ignored

### ISSUE THREAD

**Issue by xppx99** [home-assistant/home-assistant-iOS#461]
Hello, 

**App version 1.5.1**

I think the bug reported in issue #199 was not solved of merged, or reappeared.

When the app detects a iBeacon Leave, the event log clearly says: 
"Not updating Zone - ID:zone.home, state: outside because iBeacon exits are ignored"

For those of us who have a nice iBeacon coverage at home, and only want to use ibeacon for zone enter/leaving this is very troublesome. 

Thanks

**Comment by jwelter1971** [comment]
Repeat of #199 and should have been fixed in #209

**Comment by olbjan** [comment]
This issue should be closed. iBeacons can make for very reliable zone entries but should never be relied upon for zone exits.

Reasons for this are that the beacon signals can be very inconsistent because of RF interference, building materials etc.

It requires multiple beacons to come close go full coverage and exits can get triggered because of the above mentioned reasons even on an iphone that is stationary on a desk. Triggering zone exits based on beacon visibility has proven to have way too many false positives and was deactivated for that reason.

**Comment by jwelter1971** [comment]
> This issue should be closed. iBeacons can make for very reliable zone entries but should never be relied upon for zone exits.
> 
> Reasons for this are that the beacon signals can be very inconsistent because of RF interference, building materials etc.
> 
> It requires multiple beacons to come close go full coverage and exits can get triggered because of the above mentioned reasons even on an iphone that is stationary on a desk. Triggering zone exits based on beacon visibility has proven to have way too many false positives and was deactivated for that reason.

With a proper iBeacon coverage design this is not the case.  What is required is a "consider home" like the wifi and other trackers to span any short coverage issues.  I've had zero issues with the old exit behavior.

**Comment by xppx99** [comment]
> This issue should be closed. iBeacons can make for very reliable zone entries but should never be relied upon for zone exits.
> 
> Reasons for this are that the beacon signals can be very inconsistent because of RF interference, building materials etc.
> 
> It requires multiple beacons to come close go full coverage and exits can get triggered because of the above mentioned reasons even on an iphone that is stationary on a desk. Triggering zone exits based on beacon visibility has proven to have way too many false positives and was deactivated for that reason.

I don't understand your reply, and I  do not understand the lack on interest in this feature and at least the availability to make it a option, for those of us who have a nice coverage with ibeacon. 

You see two users who need this feature (which in fact is still broken, because the toggle in Notification exit ibeacon still remains available), who report that have nice coverage, and you (the most expert man in RF signals, for sure) ignore this and suggest it is closed. I've zero false exit failures with Owntracks in my home. 

Rationaly what would make sense at least was the option to make it booleano setting: 
**Ignore iBeacon exit (on or off)**

**Comment by olbjan** [comment]
Hi,

I'm not suggesting I know any better about this and it hasn't been my decision. I was however among the few people who volunteered to test the iBeacon implementation and when it was tested, there were many false positives within the group of testers. The option to get an alert for ibeacon zone exits exists in the app so this could be verified by people that complained about automations triggering zone exists.
While it may be true that your setup has perfect coverage and you never have RF interference from WiFi, neighbours or microwave ovens, the same cannot be said for others and I believe Robbie decided that iBeacons were too unreliable for him to support them for this feature. Adding the option to enable them in this way was suggested but was not adopted.

I'm just here trying to explain about a year after this was tested and decided what the reasons were for the current design.

**Comment by xppx99** [comment]
Hi,
iBeacon operates in the same frequency than WiFi, bluetooth, but it is a low power signal. 
Signal streng vs coverage is the most probable cause of the problems you and others reported when testing, not the RF interference from other RF equipments. 

Anyway, I achieve the same goal by using OwnTracks (setting the home zone to
Passive and defining an iBeacon zone in OwnTracks with the name home) and works really well for me. I was hopping to just have to use one app for this purpose (the home assistant app...) but I guess this won’t change anytime soon.  

It is still a bad decision in my opinion - ibeacons implementation is half done / broken. 
I'll bother you or devs no more with this subject.
